/** Contexte partagé entre modules game/* (initialisé par game.js). */
export const shared = {
  game: null,
  MAX_FLOORS: 8,
  pads: [],
  paths: [],
  SPIRE_LAYOUTS: [],
  MAP_LANE_CONFIG: null,
  MAP_NODE_POOL: [],
  TOOLTIPS_CONFIG: null,
  NODE_OBJECTIVE_LIBRARY: [],
  WAVE_MODIFIER_LIBRARY: [],
  ENCOUNTER_CONFIG: null,
  EVENT_LIBRARY: [],
  BIOMES: [],
  CARD_LIBRARY: [],
  MUTATION_LIBRARY: [],
  towerTypes: {},
  enemyTypes: {},
  onboarding: null,
  mobileShell: null,
  runMusic: null,
  sfx: null,
  canvas: null,
  ctx: null,
  mapChoicesEl: null,
  mapFloorLabel: null,
  mapRouteHintEl: null,
  startWaveBtn: null,
  combatObjectiveBanner: null,
  titleModePanel: null,
  titleVersionEl: null,
  cancelPlacementBtn: null,
  showMessage: () => {},
  playSound: () => {},
  gainScore: () => {},
  setScreen: () => {},
  hideMapOverlay: () => {},
  showMapOverlay: () => {},
  hideShopOverlay: () => {},
  showShopOverlay: () => {},
  openCrossroadsReward: () => {},
  handleNonCombatNode: () => {},
  setEncounterForNode: () => {},
  resetEncounterState: () => {},
  renderTowerShopButtons: () => {},
  applyBiomeForCurrentFloor: () => {},
  getBiomeForFloor: () => ({}),
  getNodeTooltip: () => "",
  tryContextHint: () => {},
  touchRunProgress: () => {},
  getRunRng: () => Math.random,
  pickNodeObjective: () => null,
  shouldRollObjective: () => false,
  pickWaveModifier: () => null,
  laneGuaranteesWaveModifier: () => false,
  getLaneAffinityHint: () => "",
  getMapLanePreview: () => [],
  generateSpireMap: () => ({ map: [] }),
  pickRandomEvent: () => null,
  EVENT_GOLD: { nectar: 40 },
};

export function initShared(partial) {
  Object.assign(shared, partial);
}
